### ISSUE TITLE
Delay between commands?

### ISSUE THREAD

**Issue by Shananium** [Nokorbis/ar-command-signs#15]
Is there a way to delay commands between rows in your pluing?

In past command sign plugins I could do something like this:
1: /bc Starting in...
2: %1
3: /bc 3!
4: %1
5: /bc 2!
6: %1
7: /bc 1!
8: %1
9: /bc GO!

Where %1 = 1 Second delay before starting next row command. %2 = 2 Second delay and so on.

**Comment by Nokorbis** [comment]
It is not possible to do that with my plugin.
The only way you could do that is by using a plugin whose command adds the delay by itself.

**Comment by Shananium** [comment]
Ok, thanks!

**Comment by mrcoffee1026** [comment]
Would you consider ADDING the ability?  It's been problematic without a delay as the commands put into a sign do not appear to always fire in the correct order.  For instance, if I set a sign with worldguard abilities like 'select' a region, then 'set' that region (say for... resetting a spleef arena)... 2 of 3 times the sign is clicked I get the error "you must select a region first" because it's trying to set before it selects.  It's great that the signs work so very fast, but in cases like this, it would be desirable to have a minimum delay between the commands so that the first one is "done" before the next command is run.

**Comment by Nokorbis** [comment]
https://www.spigotmc.org/resources/command-signs.10512/update?update=207801
