### ISSUE TITLE
can't create sign.

### ISSUE THREAD

**Issue by mrcoffee1026** [Nokorbis/ar-command-signs#16]
/commandsigns create
result is "Wrong CommandSigns command syntax".  Tried at least a dozen parameters.

Can't edit signs made in any previous version error is: "Not a command sign"

Since new ones cannot be made, this plugin has no purpose?

**Comment by Nokorbis** [comment]
So you have updated the plugin and then commands weren't working anymore ?
From what version of the plugin to what version have you updated ?

**Comment by mrcoffee1026** [comment]
I'm not sure what the prior version was that I had, it looked to be a bit before this one... I deleted the folder and started with a fresh copy.  When it still didn't let me make my signs again, I reverted to one version prior (1.5.3).  This version lets me make signs although doesn't obey the delay syntax (%seconds).  I'm not confident, but i may have had 1.5.0 prior to the attempted upgrade.  Whatever it was, it already had the altered folder name (commandsignS) and .json storage for the signs... which... based on the documentation, I'm guessing you don't use any longer since your example is a numbered file that is not in json format.  In any case the "create" command needs to be fixed or include some sort of documentation as to what syntax is supposed to be used for it to work.

**Comment by Nokorbis** [comment]
There is no delay syntax on my plugin. This is a feature I've never added. (At least, not between commands, only before the execution of all commands).
I'm still using .json format, the main difference is that each command sign has its own file and are not regrouped in a single file anymore.

What surprises me is when you said you tried with dozens of parameters while the create command doesn't require one.

Anyway, I don't think the problem is coming from my command. It works well on my server and many people actually use it on other servers without any problem. Haven't you installed any other plugin in the mean time ?
What are you using for your server ? Spigot or Craftbukkit ? What version ?

**Comment by mrcoffee1026** [comment]
I tried a dozen parameters because I got the error when entering no parameters.  According to your wiki, you have a delay syntax... or HAD a delay syntax before you removed the page from the wiki.  It was the example that included every option.  You had a %5 on a single line stating the commands on the remaining lines would be run 5 seconds later, and that this approach would not cause any lag.  When I attempted to enter the %5 before a command it simply printed "%5" into chat followed by whatever command I set... all text is chatted by the player.  If this works differently in your current version... that's fine and well, but I can't run it currently.  It's coming from your command alright?  Since a roll back to the previous version remedies the issue (that is, I can create and edit signs again).  In the mean time I'm using the version one step prior to the current since it still works... except for the delays which... seem to have mysteriously vanished since I brought them up.

Spigot is a version of CraftBukkit
Version 1.12.2-R0.1-SNAPSHOT

**Comment by Nokorbis** [comment]
As I said, I have never developed a delay syntax. You must be mistaking my plugin with someone else's one.
There are 2 or 3 plugins named "Command Signs" so that would not be a surprise.
This could even be a fork from my own plugin by someone else since mine is open source.

**Comment by mrcoffee1026** [comment]
I'm not going to argue about this, it was in the docs before my comment.  In any case /commandsign create doesn't work in the latest release, so please let me know when this works again.

**Comment by Nokorbis** [comment]
> Spigot is a version of CraftBukkit  

Yeah and no, Spigot has some more features that CraftBukkit has not. (For instance, the Gson Serializer that I use in my plugin). That's why I'm asking.

I don't have enough data to help you fix your problem. The plugin works for me on local, on my own server and for many other servers administrators. Do you have any error message in the console log ?

**Comment by mrcoffee1026** [comment]
Yeah I already said, it's an error from the plugin itself stating that it's not the correct syntax.  This is the only error provided, I'm not getting anything from the server itself.  The bothersome thing is when attempting to edit a pre-existing sign it says it's not a command sign, so I can't edit previously created ones.  I don't know if previously created signs would work, but since you say "it works", I assume that - so long as no one has to change any existing signs or add any new ones, it's fine.

**Comment by Nokorbis** [comment]
Have you redownloaded from here (https://www.spigotmc.org/resources/command-signs.10512/) since then ?
I've checked my whole project, there is no line of code saying "Wrong syntax"

**Comment by mrcoffee1026** [comment]
well downgrading to the prior version fixed it... i redownloaded the recent one again and it was fine so, no idea.  Thanks for the time.
