### ISSUE TITLE
Command signs giving permissions for $

### ISSUE THREAD

**Issue by saltysquashh** [Nokorbis/ar-command-signs#27]
I tried setting a command block up that would give the player a permission, by using "Temporary Permissions". It asked for command string, but i don't know much about all this, so i tried using the node of the command. Then i realized that i did something wrong, because string is something else.

This is not an issue, i just don't know if this is even possible. Thank you.

**Comment by Nokorbis** [comment]
It asked for a command string ?  When you tried to add a permission ?
I don't understand what you've tried and what you are trying to do.
Maybe you can post a screenshot of your current configuration ?

But note that temporary permissions are only there to grant the permissions that are needed to run the commands you put on the command signs. So if you add a command to teleport the player, you need to add a temporary permission that is required to use the teleportation command so that the player can actually teleport (or else they will receive a message saying they do not have the permission)
